#FROM maven:3.8.6-openjdk-11 as builder
FROM chainweaver/mira-job-service:v1.1.0 as builder

WORKDIR /home/workspace
COPY ./target/mira-job-service-1.1.0-SNAPSHOT.jar /home/workspace/mira-job-service-1.1.0-SNAPSHOT.jar
CMD [ "java", "-jar", "mira-job-service-1.1.0-SNAPSHOT.jar" ]
