server:
  address: 0.0.0.0
  port: 5005

management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露metrics端点
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true #
