# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
spec:
  arguments:
    parameters:
    - name: git_repo
      value: git@git.code.tencent.com:ChainWeaver/mira/mira-backend-service.git
    - name: git_sha
      value: 92a60b52f1f81e5eb9e143ad787336811282c00d

  entrypoint: entry
  workflowTemplateRef:
    name: java-build-template-v1