chain_client:
  chain_id: "chain_dcwjo"
  org_id: "69vkhyqorg.cm-95tn70edqz"
  user_key_file_path: "certs/tls.key"
  user_crt_file_path: "certs/tls.crt"
  user_sign_key_file_path: "certs/sign.key"
  user_sign_crt_file_path: "certs/sign.crt"
  nodes:
    - # 节点地址，格式为：IP:端口:连接数192.168.0.202:12301
      "node_addr": "172.16.12.240:30010"
      # 节点连接数
      conn_cnt: 100
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "certs/ca"
      tls_host_name: "consensus1-69vkhyqorg.cm-95tn70edqz"
  archive:
    # 数据归档链外存储相关配置
    type: "mysql"
    dest: "root:123456:localhost:3306"
    secret_key: xxx
  rpc_client:
    # grpc客户端最大接受容量(MB)
    max_receive_message_size: 16
